### ISSUE TITLE
polygon subset including unexpected dimensions 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#109]
@bkonzil 
polygon subsetting failed with the ocgis clipping in case of unexpected dimensions:

float landCoverFrac(time, type, lat, lon) ;
        landCoverFrac:standard_name = "area_fraction" ;
        landCoverFrac:long_name = "Plant Functional Type Grid Fraction" ;

**Comment by nilshempelmann** [comment]
Will be fixed with:
https://github.com/NCPP/ocgis/issues/374

**Comment by huard** [comment]
@nilshempelmann Is this still relevant ?

**Comment by nilshempelmann** [comment]
NCPP/ocgis#374 is closed. So we can close this one as well. 
@huard : Thanks for the observation!
