### ISSUE TITLE
update to ocgis-next=1.4.0.dev1=py27_1

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#128]
All dependencies have to adjust ....

**Comment by nilshempelmann** [comment]
pinn @cehbrecht @bekozi
ocgis is not handling multifile lists after update: 

Related issue:
https://github.com/bird-house/flyingpigeon/issues/29

netcdf4 MFDataset seem to be fine:

[u'lat', u'lon', u'time', u'slp']

**********************
 but ocgis gives an error:

Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/scripts/netCDF4test.py", line 17, in <module>
    print rd.inspect() 
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", line 415, in inspect
    return self.driver.inspect()
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/base.py", line 97, in inspect
    for line in Inspect(request_dataset=self.rd).get_report_possible():
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", line 107, in get_report_possible
    if self.variable is None:
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", line 52, in variable
    ret = self.request_dataset.variable
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", line 386, in variable
    self._variable = get_tuple(self.driver.get_dimensioned_variables())
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", line 88, in get_dimensioned_variables
    metadata = self.raw_metadata
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", line 42, in raw_metadata
    ds = self.open()
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", line 51, in open
    ret = nc.Dataset(self.rd.uri, 'r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: No such file or directory
(flyingpigeon) nils@dove:~/data/tests$

**Comment by bekozi** [comment]
@nilshempelmann Where is the reproducer for this? Nothing changed in `ocgis` next except support for the new `icclim` version. So...very odd.

**Comment by nilshempelmann** [comment]
It changed the netcdf conda version. former ocgis was build with 
netcdf4=1.2.2 now it requires netcdf4=1.2.4.

And this causes the error. We ll search further next week.

Bon week-end
Nils

**Comment by bekozi** [comment]
This should be fixed in the updated `ocgis-next` package. `netcdf4-python` changed an exception class in the recent version so the single and multiple URI check was failing. Let me know how it goes!

**Comment by nilshempelmann** [comment]
Hi Ben

There is the devil somewhere.

I created a new environment:

   140  conda create -n ocgis -c nesii ocgis-next
   141  source activate ocgis
   142  python scripts/netCDF4test.py

So should be your version. But still recieve the error while running the 
script:


Traceback (most recent call last):
   File "scripts/netCDF4test.py", line 22, in <module>
     print rd.inspect()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", 
line 415, in inspect
     return self.driver.inspect()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/base.py", 
line 97, in inspect
     for line in Inspect(request_dataset=self.rd).get_report_possible():
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", 
line 107, in get_report_possible
     if self.variable is None:
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", 
line 52, in variable
     ret = self.request_dataset.variable
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", 
line 386, in variable
     self._variable = get_tuple(self.driver.get_dimensioned_variables())
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 88, in get_dimensioned_variables
     metadata = self.raw_metadata
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 42, in raw_metadata
     ds = self.open()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 51, in open
     ret = nc.Dataset(self.rd.uri, 'r')
   File "netCDF4/_netCDF4.pyx", line 1811, in 
netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: No such file or directory
(ocgis) nils@dove:~/birdhouse/flyingpigeon$ history |


This is my conda environmet:

(ocgis) nils@dove:~/birdhouse/flyingpigeon$ conda list
# packages in environment at /home/nils/.conda/envs/ocgis:
#
Using Anaconda API: https://api.anaconda.org
click                     6.6                      py27_0
cligj                     0.4.0                    py27_0
curl                      7.49.0                        1
fiona                     1.7.0                    py27_0
gdal                      2.1.0                    py27_0
geos                      3.5.0                         0
geotiff                   1.4.1                         0
hdf4                      4.2.12                        0
hdf5                      1.8.17                        1
jbig                      2.1                           0
jpeg                      8d                            1
kealib                    1.4.6                         0
krb5                      1.13.2                        0
libgdal                   2.1.0                         0
libnetcdf                 4.4.1                         0
libtiff                   4.0.6                         2
mkl                       11.3.3                        0
cf_units                  1.1                      py27_0    nesii
click-plugins             1.0.3                    py27_0    nesii
icclim                    4.2.5                    py27_0    nesii
libspatialindex           1.8.5                         0    nesii
munch                     2.0.4                    py27_0    nesii
ocgis-next                1.4.0.dev1               py27_2    nesii
proj.4                    4.9.2                         0    nesii
rtree                     0.8.2                    py27_0    nesii
udunits2                  2.2.20                        0    nesii
netcdf4                   1.2.4               np111py27_0
numpy                     1.11.1                   py27_0
openssl                   1.0.2j                        0
pip                       8.1.2                    py27_0
proj4                     4.9.2                         0
python                    2.7.12                        1
readline                  6.2                           2
setuptools                27.2.0                   py27_0
shapely                   1.5.16                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
xerces-c                  3.1.4                         0
xz                        5.2.2                         0
zlib                      1.2.8                         3
(ocgis) nils@dove:~/birdhouse/flyingpigeon$

**Comment by bekozi** [comment]
Devil is the right word. Can you run this script?: https://gist.github.com/bekozi/76f2405de129dc7db370c90eeb54a30b. It is what I've been using for testing the uploaded packages. Works for me.

```
docker run -id --name test-runner bekozi/ntest-ubuntu
docker exec test-runner bash -c "conda install -c nesii ocgis-next wget"
docker exec test-runner bash -c "git clone https://gist.github.com/76f2405de129dc7db370c90eeb54a30b.git test_mfdataset"
docker exec test-runner bash -c "python test_mfdataset/test_mfdataset.py"
docker stop test-runner
```

**Comment by nilshempelmann** [comment]
No...

(ocgis) nils@dove:~/birdhouse/flyingpigeon$ python 
scripts/netCDF4test_ben.py
100% 
[..........................................................................] 
5983955 / 5983955URI = slp.2008.nc
VARIABLE = slp

=== Temporal =============

Name = time
Count = 366
Has Bounds = False
Data Type = float64
Start Date = 2008-01-01 00:00:00
End Date = 2008-12-31 00:00:00
Calendar = standard
Units = hours since 1800-01-01 00:00:0.0
Resolution (Days) = 24

=== Spatial ==============

.....


Converted to chunked, deflated non-packed NetCDF4 2014/09 ;
     :References = 
http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html ;
     :dataset_title = NCEP-NCAR Reanalysis 1 ;
None
**********************
[u'lat', u'lon', u'time', u'slp']
**********************
Traceback (most recent call last):
   File "scripts/netCDF4test_ben.py", line 26, in <module>
     print rd.inspect()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", 
line 415, in inspect
     return self.driver.inspect()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/base.py", 
line 97, in inspect
     for line in Inspect(request_dataset=self.rd).get_report_possible():
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", 
line 107, in get_report_possible
     if self.variable is None:
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/util/inspect.py", 
line 52, in variable
     ret = self.request_dataset.variable
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/base.py", 
line 386, in variable
     self._variable = get_tuple(self.driver.get_dimensioned_variables())
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 88, in get_dimensioned_variables
     metadata = self.raw_metadata
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 42, in raw_metadata
     ds = self.open()
   File 
"/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py", 
line 51, in open
     ret = nc.Dataset(self.rd.uri, 'r')
   File "netCDF4/_netCDF4.pyx", line 1811, in 
netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: No such file or directory
(ocgis) nils@dove:~/birdhouse/flyingpigeon$

**Comment by bekozi** [comment]
Check your paths. You are activating the "ocgis" environment, but that is not the environment that the software is being called from:

/home/nils/**.conda/envs/flyingpigeon**/lib/python2.7/site-packages/ocgis/api/request/driver/nc.py

It must be an environment issue on your machine...

**Comment by nilshempelmann** [comment]
good point. This seems fine:

(ocgis) nils@dove:~/birdhouse/flyingpigeon$ which python
/home/nils/.conda/envs/ocgis/bin/python
(ocgis) nils@dove:~/birdhouse/flyingpigeon$ echo $PATH
/home/nils/.conda/envs/ocgis/bin:/home/nils/.conda/envs/flyingpigeon/bin:/home/nils/anaconda/bin:{/home/nils/.conda/envs/flyingpigeon/bin:/home/nils/anaconda/bin:{/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games}} 

(ocgis) nils@dove:~/birdhouse/flyingpigeon$


But this may be causes the troubles:

echo $PYTHONPATH
/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/:/home/nils/birdhouse/flyingpigeon:{/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/:/home/nils/birdhouse/flyingpigeon:{}} 

(ocgis) nils@dove:~/birdhouse/flyingpigeon$

**Comment by bekozi** [comment]
I would unset `$PYTHONPATH` and try again. It doesn't play nice with Anaconda in general.

**Comment by nilshempelmann** [comment]
That was the trick !!!

could run it now!

Than should be able to run in birdhouse as well ....

Merci
Nils

**Comment by bekozi** [comment]
:+1:

**Comment by nilshempelmann** [comment]
environment.yml updated in master

**Comment by nilshempelmann** [comment]
Not running on CentOS. due to gdal conflicts

**Comment by nilshempelmann** [comment]
updated to ocgis-next=1.4.0.dev1=py27_3
