### ISSUE TITLE
Analogues Viewer: handle case when no config file exists

### ISSUE THREAD

**Issue by KatiRG** [bird-house/flyingpigeon#132]
e.g. when input file comes from a2c2 directory, not from an analogues detection process

**Comment by nilshempelmann** [comment]
@KatiRG 
If parameter are None, the defaut values defined in the fuction to write the config file will be set and an default config file will be created.
Check the default values and change them ( or create sense-full arguments ) to create a working config file
https://github.com/bird-house/flyingpigeon/blob/master/flyingpigeon/analogs.py#L5

**Comment by KatiRG** [comment]
This issue is for the analogues viewer process which reads in the number of analogues from the config file https://github.com/bird-house/flyingpigeon/blob/master/flyingpigeon/processes/wps_analogs_viewer.py#L86

Must handle case where no config file exists, ie when user does not first run `analogs.py` but directly inputs `file:///home/` input file.

**Comment by KatiRG** [comment]
looks like i can find out if file exists by checking the status code:

> r = requests.get(configfile_with_path)
>             if r.status_code != 404:

**Comment by KatiRG** [comment]
@nilshempelmann How do I create a new file? I tried

```
ip, config_file = mkstemp(dir=outputUrl_path,suffix='.txt')
configfile = open(config_file, "w")
configfile.write( 'test' )
configfile.close()
```
but get the error:
`No such file or directory: 'http://localhost:8090/wpsoutputs/flyingpigeon/tmppc5S7m.txt'`

I don't know why it is looking for this file, I am trying to create it...

**Comment by nilshempelmann** [comment]
I ll answer in the developer chat room.

**Comment by nilshempelmann** [comment]
Done
