### ISSUE TITLE
fix conda dependencies ... conflict with icu package

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#165]
packages on defaults channel were updated by conda and there is now a conflict with packages from conda-forge. Looks like somepackages (defaults?) want `icu=56` while others want `icu=58`.

**Comment by cehbrecht** [comment]
tried to pin icu=58.1 but it looks like either ocgis or one of its dependencies doesn't like it.

**Comment by cehbrecht** [comment]
conda env works on my dev machine (ubuntu) and on travis ... merged to master.

**Comment by nilshempelmann** [comment]
Fixed
