### ISSUE TITLE
Weather regime process optimisation of subsetting

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#17]
Data preparation is performed with ocgis and cdo commands.

subsetting over the median (longitude = 0) with ocgis results in dividing the domain (see: [https://github.com/bird-house/flyingpigeon/blob/master/notebooks/cdo_ocgis.ipynb](url) ) 
While cdo needs a cdo cat or cdo mergetime (not possible when datafiles are heterogen e.g. only containing sometimes variables like time_bnds) before performing the subsetting of a bounding box.

**Comment by bekozi** [comment]
It sounds like you need a ``vector_wrap`` option that applies to the dataset. I think this should go on the ``RequestDataset`` with options like:

- ``wrap=True`` Wrap to -180 to 180.
- ``wrap=False`` Unwrap to 0 to 360.
- ``wrap=None`` (Default) Leave as is.

Have you tested with a "wrapped" grid?

**Comment by nilshempelmann** [comment]
Nice idea. 
but but rising the heterogeneity of girds can cause problems in the post processing. 
 cdo is handling it like that (updated the notebook):

print lon[:]
[-78.75  -76.875 -75.    -73.125 -71.25  -69.375 -67.5   -65.625 -63.75
 -61.875 -60.    -58.125 -56.25  -54.375 -52.5   -50.625 -48.75  -46.875
 -45.    -43.125 -41.25  -39.375 -37.5   -35.625 -33.75  -31.875 -30.
 -28.125 -26.25  -24.375 -22.5   -20.625 -18.75  -16.875 -15.    -13.125
 -11.25   -9.375  -7.5    -5.625  -3.75   -1.875   0.      1.875   3.75
   5.625   7.5     9.375  11.25   13.125  15.     16.875  18.75   20.625
  22.5  ]

would it be possible to be consistent with that?

Merci 
nils

**Comment by bekozi** [comment]
Yeah, that should be possible. The data needs to be wrapped before the subset otherwise the masked values will be an issue.

**Comment by nilshempelmann** [comment]
Done
