### ISSUE TITLE
ncep Data failed with ocgis

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#174]
@bekozi

NCEP data are processed with single files but are failing with multiple files.

**Comment by nilshempelmann** [comment]
related to this issue: https://github.com/NCPP/ocgis/issues/444
workaround: data convertion while fetching to local server

**Comment by nilshempelmann** [comment]
fixed with workaround: 
MFDataset can not handle NETCDF4. Converting to NETCDF4_CLASSIC while fetching the data. 
pushed to branch pywps4

**Comment by nilshempelmann** [comment]
bug is back :-(

**Comment by nilshempelmann** [comment]
Found the bug :-)

Convention is possible with the latest ocgis version. The conda package ocgis==2.0.0 is not including the latest bugfixes.

@bekozi  could you provide an actual ocgis package?

**Comment by bekozi** [comment]
Hi. I'll be able to update the conda package by tomorrow (we'll need to use a development build). In the meantime, feel free to install the latest code from `master`.

**Comment by nilshempelmann** [comment]
ocgis-next=2.0.1 integrated. 
bug fixed
