### ISSUE TITLE
land sea mask fails

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#175]
ESGF search fails

**Comment by nilshempelmann** [comment]
Here is an error:
....
hlight">Remember my OpenID</span> on this computer</td></tr>             </table></td></tr></table></div></td></tr></table></form>  <br>        <p/>&nbsp;<p/>After logging in, you will be redirected to: <br/><b>http://cordexesg.dmi.dk/thredds/dodsC/cordex_general/cordex/output/NAM-44/UQAM/MPI-M-MPI-ESM-LR/historical/r1i1p1/UQAM-CRCM5/v1/fx/sftlf/v20160831/sftlf_NAM-44_MPI-M-MPI-ESM-LR_historical_r1i1p1_UQAM-CRCM5_v1_fx.nc.dds</b><p/>&nbsp;<p/>        </td></tr>   <tr><td></td></tr>    </table>   </body> </html>
cdo gtc: Open failed on >http://cordexesg.dmi.dk/thredds/dodsC/cordex_general/cordex/output/NAM-44/UQAM/MPI-M-MPI-ESM-LR/historical/r1i1p1/UQAM-CRCM5/v1/fx/sftlf/v20160831/sftlf_NAM-44_MPI-M-MPI-ESM-LR_historical_r1i1p1_UQAM-CRCM5_v1_fx.nc<
Unknown Error

**Comment by cehbrecht** [comment]
tried the same file on our demo service ... and it worked. There was a shutdown over the weekend of the esgf service and you also need a valid esgf credential.

**Comment by nilshempelmann** [comment]
Outdated : Land sea masking is disabled
