### ISSUE TITLE
indices.calc_indice_percentile returns false output

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#200]
See the code:

https://github.com/bird-house/flyingpigeon/blob/master/flyingpigeon/indices.py#L280

This functions is currently "under construction" ... but it returns a false output.

See also PR #199

**Comment by cehbrecht** [comment]
PR #201 disables this function so it can't be used accidentally.

**Comment by nilshempelmann** [comment]
indice_percentile is not supported anymore in ocgis. The process is replaced by wps_indices_percentiledays
