### ISSUE TITLE
add cosine distance to analoge process

### ISSUE THREAD

**Issue by sradanov** [bird-house/flyingpigeon#21]
castf90 now supports cosine distance.

**Comment by nilshempelmann** [comment]
@sradanov
how to add that?

**Comment by sradanov** [comment]
allow to select "cosine" in the configuration mask.

**Comment by nilshempelmann** [comment]
literalinput as 'Boolean' implemented

      identifier="cosine",
      title="Cosine Distance",
      abstract="Cosine Distance",
      default=True,

**Comment by nilshempelmann** [comment]
done
