### ISSUE TITLE
Dedicated regridding process

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#217]
I think it would be useful to have a dedicated regridding process.

**Comment by nilshempelmann** [comment]
Thats in hummingbird the remap process: 
https://bovec.dkrz.de/processes/execute?wps=hummingbird&process=cdo_inter_mpi 
But could be included in flyingpigeon as well. hummingbird is running with cdo, flyingpigoen could do it with ocgis

**Comment by nkadygrov** [comment]
And we need to add there output of first netcdf regridded file (not only tar). 
I will also write simple process from that one with further subsetting:
we have regrid process and subset process, not sure how to chain them...

**Comment by huard** [comment]
Aha ! Thanks, missed that. Not so familiar with hummingbird. So let's do it with ocgis then.

**Comment by bekozi** [comment]
Definitely keep me in the loop as this progresses.

**Comment by nkadygrov** [comment]
Also there is no option to regrid to another netCDF file.
I also tried to use ocgis, like here: http://ocgis.readthedocs.io/en/latest/examples.html#regridding
but had some troubles with import ESMF. But definitely it will be useful and again, independent from cdo.
