### ISSUE TITLE
add output format option (ascii or netcdf4) to analoges process

### ISSUE THREAD

**Issue by sradanov** [bird-house/flyingpigeon#22]
castf90 now supports netcdf4 output (beside ascii output which is still default).
Some global attributes need therefore to be defined in the configuration file.

**Comment by sradanov** [comment]
config file:

&FILES
 my_files%archivefile = "/home/scratch01/sradanov/A2C2/NCEP/base_hgt_NA_197
3-01-01_2012-12-31_-80.0_50.0_22.5_70.0.nc"
 my_files%simulationfile = "/home/scratch01/sradanov/A2C2/NCEP/sim_hgt_NA_2
013-12-01_2014-02-28_-80.0_50.0_22.5_70.0.nc"
 my_files%outputfile ="/home/estimr2/sradanov/A2C2/ana_hgt_500_rms_NA_sim_2
013-12-01_2014-02-28_base_1973-01-01_2012-12-31_-80.0_50.0_22.5_70.0_1_30_2
0.txt"
/
&PARAM
 my_params%timewin = 1
 my_params%varname = "hgt"
 my_params%seacyc = .TRUE.
 my_params%cycsmooth = 91
 my_params%nanalog = 20
 my_params%seasonwin = 30
 my_params%distfun = "rms"
 my_params%calccor = .TRUE.
 my_params%oformat = ".txt"        ! if equals ".nc" netcdf is written
 my_params%silent = .FALSE.
/
&ATTS
 my_atts%simsource = "NCEP"  ! something like model name ...
 my_atts%predictorvar = "hgt" ! as my_params%varname 
 my_atts%archisource = "NCEP"
 my_atts%archiperiod = "1973-01-01,2012-12-31" ! the format is not very important at the moment, as long as everything is in double quotes.
 my_atts%predictordom = "-80.0,50.0,22.5,70.0"
/

**Comment by nilshempelmann** [comment]
done
