### ISSUE TITLE
xarray does not load on clone install 

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/flyingpigeon#222]
Not sure if we're interested in repo clone functionality, but I'm having trouble running most birds on my local machine. Installation fails due to xarray failing to load. wheel extension is also reporting unable to load wheels. I've tried installing xarray via pip and conda but flyingpigeon (and other birds) continue to fail.

Not sure what I'm missing here. Shouldn't most depends build from conda on install?

**Comment by nilshempelmann** [comment]
We should discuss that in the chat: 
https://gitter.im/bird-house/birdhouse

**Comment by Zeitsperre** [comment]
Details posted. I've tried with Emu and Flyingpigeon. Will try with others and report back.

**Comment by huard** [comment]
@Zeitsperre  Can this be closed ? Cannot reproduce.

**Comment by Zeitsperre** [comment]
This may have been due to user error (not having the proper pywps version). If it comes up again, I'll reopen. Thanks.
