### ISSUE TITLE
NCEP data inconsitency

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#23]
fetching slp 2015 rises an error:
ERROR: Failed to execute WPS process [analogs]: failed to fetch input files (returncode:1) cdo cat (Abort): Input streams have different number of variables per time step!

**Comment by sradanov** [comment]
Ach das hatte ich auch schon mal wo. Ich glaube ab 2015 ist die variable time_bounds dabei. Das heisst man mus vorher die richtigen variablen auswaehlen, oder die time_bounds raus schmeissen.

**Comment by nilshempelmann** [comment]
files of datasets are concatenated by ocgis first. with the variable argument, the file metadata inconsistency can be handled
