### ISSUE TITLE
GDAL 2.1.3 Broken on Anaconda

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/flyingpigeon#257]
https://github.com/bird-house/flyingpigeon/blob/678370bf428af7ffe11ee79be3b8a89c73215e5e/environment.yml#L83

GDAL 2.1.3 has been retired. I suggest we move the setup to a newer version (2.2.4 or 2.3.1).

**Comment by nilshempelmann** [comment]
Changing versions is a delicate operation. Do it in a branch and make sure the envirment will be stable

**Comment by cehbrecht** [comment]
Not really a solution but one can use the `broken` channel from anaconda:
https://anaconda.org/conda-forge/gdal/files

**Comment by nilshempelmann** [comment]
I already cleaned out the R-dependencies. 
@Zeitsperre checkout the next branch and update there. fixing dependencies is tricky ...

**Comment by cehbrecht** [comment]
environment is updated and working with `gdal=2.2.4` on master branch.
