### ISSUE TITLE
Use self.workdir in processes to get working directory

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#269]
With the latest pywps you *need* to use `self.workdir` in processes to get the working directory temp folder. 

In previous versions you could assume that the current directory would be the working directory, but pywps is not allowed to switch the directory anymore.

Please see an example in hummingbird:
https://github.com/bird-house/hummingbird/blob/e8d9762eff35fd940023e8523d2c9a076843da64/hummingbird/processes/wps_cdo_sinfo.py#L72

**Comment by nilshempelmann** [comment]
DONE
