### ISSUE TITLE
only support Python 3.6?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#270]
... if so, we can disable Python 2.7 in `.travis.yml` and skip the `six` package.

We can not support Python 3.7 yet. This needs fixes in pywps and owslib.

**Comment by Zeitsperre** [comment]
Given that most of the birds install an instance of Miniconda3 on build, I get the impression that system python isn't an issue. In fact, for `raven`, I've set our travis.yml to build `language: generic` to save on time. If that's the case, I imagine we can move forward with only one Python. If we want to transition away from it, we could set a date and add deprecation warnings?

**Comment by nilshempelmann** [comment]
@cehbrecht For the processes left over in the streamlined Flyingpigeon.v1.4.x I do not see a need for Python 2.7. We can disable 2.7 in `.travis.yml`

**Comment by nilshempelmann** [comment]
py2.7 disabled in `next` branch

**Comment by nilshempelmann** [comment]
DONE
