### ISSUE TITLE
multiple file output using the MetaLink standard

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#273]
If solved in `emu` we can implement it in `flyingpigoen`
https://github.com/bird-house/emu/issues/64

**Comment by huard** [comment]
Now solved in emu.

**Comment by nilshempelmann** [comment]
Will do that for the subsetting processes. 
Looping over the single input files and get rid of the tar archive solution!

**Comment by nilshempelmann** [comment]
Done for subset processes.
(not so useful for the current plotting processes)
