### ISSUE TITLE
sphinx read the docs is not compiling

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#279]
No automatic update of the read the docs since 

https://readthedocs.org/projects/flyingpigeon/builds/

**Comment by cehbrecht** [comment]
@nilshempelmann I have run a manual build on RTD ... works. The github trigger got somehow lost ... added again:
https://readthedocs.org/dashboard/flyingpigeon/integrations/

I have made you maintainer to make changes on rtd:
https://readthedocs.org/dashboard/flyingpigeon/users/

**Comment by nilshempelmann** [comment]
Great, thanks
Done
