### ISSUE TITLE
Subset WFS Polygon returns an Xarray object

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/flyingpigeon#289]
https://github.com/bird-house/flyingpigeon/blob/56b5f4e9d4b8fa9354fe8151f58d7596762a07ea/flyingpigeon/processes/wps_subset_wfs_polygon.py#L97

@huard I'm continuing work on Raven and am wondering if we want to maintain the behaviour that OCGIS performs in this WFS process, that is to return an Xarray object rather than a NetCDF. It seems to me that a NetCDF file would be preferable as this can be written on the server and downloaded/accessed from xarray as well as netcdf4 libraries.

I also noted that the returned object can be manipulated on the user side even if they don't load the xarray library in their script (?). This seems like really strange behaviour.

Should we be converting the xarray object to `netcdf-cf` format before appending it to the WPS reponse?

**Comment by huard** [comment]
We are returning a netCDF file. 

I think you are confusing the process description with the birdy interface. Birdy recognizes that the output is a netCDF file, and if `asobj` is True, will try to open it using xarray, and if that fails, using netCDF4. The xarray import occurs inside birdy. If `asobj` is False, you'll get the url to the remote netCDF file.

**Comment by Zeitsperre** [comment]
That makes a lot of sense. Thanks!
