### ISSUE TITLE
IO error while subsetting polygons

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#29]
import wget
resource = []
for year in range(2000, 2010):
   url =
     'http://www.esrl.noaa.gov/psd/thredds/fileServer/Datasets/ncep.reanalysis.dailyavgs/surface/slp.%s.nc'
     % year
    resource.append(wget.download(url))

from ocgis import RequestDataset, OcgOperations
rd =  RequestDataset(resource[0])
rd.inspect() # works fine 
rd =  RequestDataset(resource)
rd.inspect() # error: 
  
IOError: No such file or directory

**Comment by nilshempelmann** [comment]
Here is the trick: 
conda install netcdf4==1.2.2
The following packages will be DOWNGRADED:

    netcdf4: 1.2.4-np110py27_1 --> 1.2.2-np110py27_0


ocgis can't handle netCDF1.2.4

**Comment by bekozi** [comment]
Bummer. What is the error you get with ``1.2.4``?

**Comment by nilshempelmann** [comment]
IOError                                   Traceback (most recent
     call last)
     <ipython-input-12-904df368ab5c> in <module>()
          12
          13 rd =  RequestDataset(resource)
     ---> 14 rd.inspect()

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/base.pyc
     in inspect(self)
         413         """
         414
     --> 415         return self.driver.inspect()
         416
         417     def inspect_as_dct(self):

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/driver/base.pyc
     in inspect(self)
          95         from ocgis.util.inspect import Inspect
          96
     ---> 97         for line in
     Inspect(request_dataset=self.rd).get_report_possible():
          98             print line
          99

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/util/inspect.pyc
     in get_report_possible(self)
         105
         106     def get_report_possible(self):
     --> 107         if self.variable is None:
         108             lines = self.get_report_no_field()
         109         else:

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/util/inspect.pyc
     in variable(self)
          50         if self._variable is None:
          51             try:
     ---> 52                 ret = self.request_dataset.variable
          53             except NoDimensionedVariablesFound:
          54                 ret = None

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/base.pyc
     in variable(self)
         384     def variable(self):
         385         if self._variable is None:
     --> 386             self._variable =
     get_tuple(self.driver.get_dimensioned_variables())
         387         try:
         388             ret = get_first_or_sequence(self._variable)

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/driver/nc.pyc
     in get_dimensioned_variables(self)
          86
          87     def get_dimensioned_variables(self):
     ---> 88         metadata = self.raw_metadata
          89         variables = metadata['variables'].keys()
          90         ret = []

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/driver/nc.pyc
     in raw_metadata(self)
          40     def raw_metadata(self):
          41         if self._raw_metadata is None:
     ---> 42             ds = self.open()
          43             try:
          44                 self._raw_metadata = NcMetadata(ds)

     /home/nils/.conda/envs/birdhouse/lib/python2.7/site-packages/ocgis-1.4.0.dev1-py2.7.egg/ocgis/api/request/driver/nc.pyc
     in open(self)
          49     def open(self):
          50         try:
     ---> 51             ret = nc.Dataset(self.rd.uri, 'r')
          52         except (TypeError, RuntimeError):
          53             try:

     netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__
     (netCDF4/_netCDF4.c:12613)()

     IOError: No such file or directory

**Comment by bekozi** [comment]
This doesn't happen with ``netCDF4-python v1.2.2``? It may be a ``netCDF4`` issue.

**Comment by bekozi** [comment]
I'm not sure what's going on here. I could not reproduce running under ``netcdf4-python 1.2.2 and 1.2.4``. I ran the script below using the Docker image ``bekozi/ocgis`` with ``1.2.2`` (the default) and ``1.2.4`` (installed from the ``conda-forge`` channel``) with no errors:

```python
import wget
import os
import ocgis

os.chdir('/tmp')
resource = []
for ii in range(2000, 2010):
    print ii
    url = 'http://www.esrl.noaa.gov/psd/thredds/fileServer/Datasets/ncep.reanalysis.dailyavgs/surface/slp.{}.nc'.format(ii)
    r = wget.download(url)
    resource.append(r)
    print(ocgis.RequestDataset(r).get().shape)
```

**Comment by nilshempelmann** [comment]
Here is the bottleneck: 
https://github.com/bird-house/flyingpigeon/blob/master/flyingpigeon/utils.py#L347

the multi file dataset of netCDF4 module (MFDataset) is not handling the file list given as resources.
for netCDF4==1.2.4 but works fine with conda install netCDF4==1.2.2

**Comment by nilshempelmann** [comment]
netCDF4 pinned to 1.2.2 in buildout

**Comment by nilshempelmann** [comment]
@bekozi 
was using 
conda install -c nesii ocgis 
which is different to 
conda install -c ioos ocgis 
in terms of the used netcdf4 version. 

since both conda build outs are outdated, a new conda ocgis should be provided

**Comment by bekozi** [comment]
The `conda-forge` repository has eclipsed the `ioos` repository. I believe they were supposed to be mirrored though.

**Comment by nilshempelmann** [comment]
pinning the conda packages should fix the dependencies 
https://github.com/bird-house/flyingpigeon/issues/46
