### ISSUE TITLE
Previous v1.5 tag/release was not using bump2version

### ISSUE THREAD

**Issue by tlvu** [bird-house/flyingpigeon#299]
## Description

Tried to `bump2version minor` on my fork, see wrong result https://github.com/tlvu/flyingpigeon/commit/a18f0ac96d5e53d20aaf492693a66b7436d15e86.

## Steps to Reproduce

```
`bump2version minor`
```
See resulting wrong commit at https://github.com/tlvu/flyingpigeon/commit/a18f0ac96d5e53d20aaf492693a66b7436d15e86, expected `1.6.0`.

**Comment by fmigneault** [comment]
This looks like the correct behaviour no?
`1.4.1 -> 1.5.0` with `minor`
Another call `bump2version minor` would do
`1.5.0 -> 1.6.0`

**Comment by cehbrecht** [comment]
I also would expect this:
> This looks like the correct behaviour no?
> `1.4.1 -> 1.5.0` with `minor`
> Another call `bump2version minor` would do
> `1.5.0 -> 1.6.0`

You can also have a patch release:
> `1.5.0 -> 1.5.1` with `patch`

**Comment by tlvu** [comment]
> I also would expect this:
> 
> > This looks like the correct behaviour no?
> > `1.4.1 -> 1.5.0` with `minor`
> > Another call `bump2version minor` would do
> > `1.5.0 -> 1.6.0`
> 
> You can also have a patch release:
> 
> > `1.5.0 -> 1.5.1` with `patch`

No because the last tag is `v1.5` so I expected `v1.6.0` on `minor` bump.  Also weird the format of the last tag changed, no patch version anymore.

**Comment by fmigneault** [comment]
In the tlvu@a18f0ac commit you referenced, last version is `1.4.1` and updated to `1.5.0`. 
I'm not sure which already applied `1.5.0` you are referencing to, and even less which `v1.5` without patch number and added `v` prefix.

**Comment by tlvu** [comment]
I was referring to this tag https://github.com/bird-house/flyingpigeon/tree/v1.5 in this repo.

**Comment by davidcaron** [comment]
Looks like the `v1.5` and `v1.4.2` tags didn't use bump2version, so the `setup.cfg` file is still at `1.4.1` on master.

**Comment by cehbrecht** [comment]
Ok ... I understand now. So, I can fix the version (1.5.0). But probably we leave the v1.5 tag as it is.

**Comment by tlvu** [comment]
Yes, have to leave the old v1.5 tag as it is.  Maybe document the release process so the same situation do not happen again.

**Comment by cehbrecht** [comment]
Fixed by PR #300. Check comments on documentation in this PR.
