### ISSUE TITLE
cfunits does not work with latest netcdf4

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#3]
workaround: pin netcdf4=1.1.1

cfunits is a requirement for ocgis. Needs to be fixed in ocgis ...

cfunits is quite old. Is cf-python the new version?
http://cfpython.bitbucket.org/

Need to ask Ben ...

**Comment by bekozi** [comment]
I noticed this a few days ago and posted an issue to cf-python: https://bitbucket.org/cfpython/cf-python/issue/12/status-of-cfunits-python. I hope to pass along a patch to David Hassell in the near-term. In the meantime, you are using the right approach!

It sounds like cfunits-python will be ported to BitBucket relatively soon....

**Comment by cehbrecht** [comment]
seems to be fixed with cfunits 1.0.0 (http://cfpython.bitbucket.org/)
