### ISSUE TITLE
Create notebooks

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#302]
## Description

FP should have notebooks providing examples of use through the birdy client.

**Comment by nilshempelmann** [comment]
first initial version: 
https://github.com/bird-house/notebooks/blob/master/flyingpigeon_birdy_subset.ipynb

**Comment by nilshempelmann** [comment]
Related: 
https://github.com/bird-house/notebooks/issues/2

**Comment by nilshempelmann** [comment]
Done. 
https://flyingpigeon.readthedocs.io/en/latest/notebooks/index.html
