### ISSUE TITLE
Flyingpigeon independend of eggshell

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#316]
## Description

Eggshell is currenlty only used by flyingpigeon. to reduce complexity, eggshell function will move back into flyingpigeon to be better in place.

**Comment by huard** [comment]
Is this really the best long-term strategy ?

**Comment by nilshempelmann** [comment]
Not for the long term but currently its a handicap. 
Eggshell needs to be redesigned according to birdhouse as a whole (including EO data etc. ).
Once we have eggshell in a good architecture with stable functions, I am happy to build flyingpigeon on it.

**Comment by nilshempelmann** [comment]
Here is a ticket for ideas to improve eggshell: 
https://github.com/bird-house/eggshell/issues/49

**Comment by nilshempelmann** [comment]
Done
