### ISSUE TITLE
readthedocs documentation failed 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#318]
## Description
Documentation is not building:
https://readthedocs.org/projects/flyingpigeon/builds/

**Comment by Zeitsperre** [comment]
@nilshempelmann Does flyingpigeon need to be fully installed/running in order to build the documentation? One way around it would be to create a `docs_environment.yml` with threadbare dependencies. This is how we've dealt with the problem on our end for other PAVICS components.

**Comment by nilshempelmann** [comment]
@Zeitsperre Don't know how to do that, could you point me to an example?

**Comment by Zeitsperre** [comment]
https://github.com/Ouranosinc/raven/blob/master/environment-docs.yml
https://github.com/Ouranosinc/raven/blob/master/.readthedocs.yml

ReadTheDocs can use Anaconda to generate a build environment and as a result, you can supply a lightweight version of the build that doesn't actually install/start the service in order to generate the documentation. So long as the Bird doesn't need to be installed, there shouldn't be an issue. I can try looking at this in the coming weeks, but Raven is a good example of how best to configure ReadTheDocs for this.

**Comment by nilshempelmann** [comment]
@Zeitsperre: Thanks. But If I get it right, you are skipping the auto-api. for that flyingpigeon needs to be completly compiled. right?

**Comment by huard** [comment]
`autodoc` needs a working installation, but some imports can be replaced by mock imports, thereby simplifying the installation process. 

I think `autoapi` is entirely static, so no installation needed.

**Comment by nilshempelmann** [comment]
Thanks @huard 
I ll give it a try.

**Comment by nilshempelmann** [comment]
`environment-docs.yml` is reduced to the minimum, but compilation of the `next branch` is still failing: 
'''
conda env create --quiet --name next --file environment-docs.yml
Collecting package metadata (repodata.json): ...working... Killed

Command killed due to excessive memory consumption
'''
https://readthedocs.org/projects/flyingpigeon/builds/10638719/

any ideas?

**Comment by huard** [comment]
mock imports.

**Comment by nilshempelmann** [comment]
@Zeitsperre need help here. Imports are mocked but build is still failing
```
[rtd-command-info] start-time: 2020-03-18T21:03:09.265486Z, end-time: 2020-03-18T21:03:18.293879Z, duration: 9, exit-code: 137
conda env create --quiet --name latest --file environment-docs.yml
Collecting package metadata (repodata.json): ...working... Killed


Command killed due to excessive memory consumption
```

**Comment by Zeitsperre** [comment]
Looking into this today.

**Comment by nilshempelmann** [comment]
Great! 
check out the PR https://github.com/bird-house/flyingpigeon/pull/319

**Comment by Zeitsperre** [comment]
This is very mysterious. It seems to crash the moment it tries creating an environment. I think something is misconfigured.

**Comment by nilshempelmann** [comment]
Here is the last running version: 
https://readthedocs.org/projects/flyingpigeon/builds/10407045/

**Comment by Zeitsperre** [comment]
The weird thing is nothing significant to the RTD build changed in the next push. I think the site itslef may have changed its memory limits or they may have implemented a change to its images that they did not add to their documentation that is causing things to break. This appears to have happened in the past month.

**Comment by nilshempelmann** [comment]
Its a small doc environment. It should run through...

**Comment by Zeitsperre** [comment]
I think there's an issue with their Anaconda image. I might have to speak with them directly.

**Comment by Zeitsperre** [comment]
Just tried using a docker image of the RtD build and everything check out fine. This is a configuration issue on their side. Contacting them today.

**Comment by nilshempelmann** [comment]
Thanks!
