### ISSUE TITLE
Refactor subsetting processes

### ISSUE THREAD

**Issue by huard** [bird-house/flyingpigeon#326]
## Description

To simplify subsetting, I suggest to remove the "mosaic" option in 
- wps_subset_continents
- wps_subset_countries 
- wps_subset_wfs_polygon

This would mean that by default, multiple geometries would be aggregated prior to subsetting. The current API allows for multiple netCDF input files (N) and multiples geometries (M), which can result in N*M output files. I believe this is too complex for a fairly rare use case.

Note that the mosaic option would be present for all of the averaging processes  (wps_average_continents, etc.), where results from each geometry can be stored along a new dimension, without multiplying the number of output files.

**Comment by huard** [comment]
@nilshempelmann Thoughts ?

**Comment by nilshempelmann** [comment]
@huard Yes we can skip the mosaic option. Its out of the early days, where we tried do design processes which can do all in one. But now its better to have simple processes being called multiple times. 
Don't know how the averaging processes will look like
