### ISSUE TITLE
Add more possible data sources to Analog process

### ISSUE THREAD

**Issue by sradanov** [bird-house/flyingpigeon#36]
Add other reanalysis such as 20CR, ERA-Interim etc.
Maybe add CMIP5 data

**Comment by nilshempelmann** [comment]
weatherregimes for reanalyses can fetch pressure and geopotential hights. 
Check the functions there, can also be moved to an separate module

**Comment by sradanov** [comment]
Yes, it would probably be a good idea to have a common module for fetching data, we just have to make sure that the file formats needed are kind of the same.

**Comment by nilshempelmann** [comment]
Module is created:
#from flyingpigeon.weatherregimes import get_NCEP 
moved to:
from flyingpigeon.datafetch import reanalyses

**Comment by nilshempelmann** [comment]
Done
