### ISSUE TITLE
pinning conda packages

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#46]
pinning required conda build-outs for stable environment

**Comment by nilshempelmann** [comment]
current environment is quite large: 
[nhempel@lsce3199 flyingpigeon]$ conda list -n birdhouse 
# packages in environment at /homel/nhempel/.conda/envs/birdhouse:
#
alabaster                 0.7.7                    py27_0  
argcomplete               1.0.0                    py27_1  
glib                      2.43.0                        2    asmeurer
libgcc                    4.8.5                         1    asmeurer
babel                     2.2.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
pymongo                   3.2.2                    py27_0    binstar
r-mclust                  5.1                    r3.2.2_0    bioconda
amqp                      1.4.8                    py27_0    birdhouse
anyjson                   0.3.3                    py27_0    birdhouse
billiard                  3.3.0.21                 py27_0    birdhouse
bird-feeder               0.2.0                    py27_0    birdhouse
castf90                   0.1.1                         3    birdhouse
cdat-lite                 6.0rc2                 nppy27_0    birdhouse
celery                    3.1.19                   py27_0    birdhouse
cfchecker                 2.0.9                    py27_0    birdhouse
esgf-pyclient             0.1.6                   py27_51    birdhouse
eventlet                  0.16.1                   py27_0    birdhouse
flower                    0.8.2                    py27_0    birdhouse
java-jdk                  8.0.45                        3    birdhouse
kombu                     3.0.32                   py27_0    birdhouse
lapack95                  3.0.0                         7    birdhouse
libuuid                   1.0.3                         2    birdhouse
nginx                     1.8.0                         0    birdhouse
owslib                    0.11.2                  py27_59    birdhouse
pygbif                    0.1.4                    py27_0    birdhouse
pyramid_celery            2.0.0                    py27_0    birdhouse
pysolr                    3.3.2                    py27_0    birdhouse
pywps                     3.2.5                    py27_4    birdhouse
qa-dkrz                   0.5.9                         2    birdhouse
r-ncdf4                   1.13                          0    birdhouse
redis                     3.0.3                         0    birdhouse
repoze.sendmail           4.2                      py27_0    birdhouse
solr                      5.2.1                         1    birdhouse
threddsclient             0.3.4                    py27_0    birdhouse
cairo                     1.12.18                       6  
cffi                      1.5.2                    py27_0  
chameleon                 2.22                     py27_0  
click                     6.3                      py27_0  
cligj                     0.4.0                    py27_0  
libiconv                  1.14                          2    conda-forge
cryptography              1.0.2                    py27_0  
curl                      7.45.0                        0  
cycler                    0.10.0                   py27_0  
dateutil                  2.4.1                    py27_0  
decorator                 4.0.9                    py27_0  
docutils                  0.12                     py27_2  
enum34                    1.1.2                    py27_0  
execnet                   1.2.0                    py27_0  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
funcsigs                  1.0.2                    py27_0  
futures                   3.0.3                    py27_0  
gcc                       4.8.5                         3  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.1                    py27_0  
greenlet                  0.4.9                    py27_0  
gunicorn                  19.1.0                   py27_0  
harfbuzz                  0.9.39                        0  
hdf4                      4.2.11                        0  
hdf5                      1.8.15.1                      2  
beautiful-soup            4.3.2                    py27_0    https://conda.binstar.org/asmeurer
dispel4py                 1.0.1                    py27_0    https://conda.binstar.org/birdhouse
expat                     2.1.0                         1    https://conda.binstar.org/birdhouse
genshi                    0.7                      py27_0    https://conda.binstar.org/birdhouse
htmltmpl                  1.22                     py27_1    https://conda.binstar.org/birdhouse
myproxyclient             1.4.3                    py27_0    https://conda.binstar.org/birdhouse
python-magic              0.4.6                    py27_1    https://conda.binstar.org/birdhouse
python-swiftclient        2.4.0                    py27_0    https://conda.binstar.org/birdhouse
icu                       54.1                          0  
idna                      2.0                      py27_0  
imagesize                 0.7.0                    py27_0  
cartopy                   0.14.2              np110py27_0    ioos
cdo                       1.7.0                         2    ioos
cf_units                  1.1                      py27_0    ioos
click-plugins             1.0.3                    py27_0    ioos
compliance-checker        2.1.0                    py27_3    ioos
ecmwf_grib                1.14.7                        3    ioos
fiona                     1.6.3               np110py27_5    ioos
freexl                    1.0.2                         0    ioos
gdal                      1.11.4              np110py27_7    ioos
geolinks                  0.1.0                    py27_1    ioos
giflib                    5.1.2                         1    ioos
gsl                       2.1                           0    ioos
iris                      1.9.2               np110py27_0    ioos
jasper                    1.900.1                       5    ioos
json-c                    0.12                          0    ioos
libspatialindex           1.8.5                         1    ioos
libspatialite             4.3.0a                        3    ioos
munch                     2.0.4                    py27_0    ioos
nco                       4.5.5                         1    ioos
netcdf-fortran            4.4.2                         0    ioos
openjpeg                  2.1.0                         0    ioos
petulant-bear             0.2.0                    py27_0    ioos
pycdo                     1.2.6                    py27_0    ioos
pycsw                     1.10.4                   py27_0    ioos
pyepsg                    0.2.0                    py27_1    ioos
pyke                      1.1.1                    py27_2    ioos
pyproj                    1.9.5.1                  py27_0    ioos
python-ecmwf_grib         1.14.7              np110py27_1    ioos
rtree                     0.8.2                    py27_2    ioos
shapely                   1.5.13              np110py27_1    ioos
wicken                    0.2.0                    py27_0    ioos
ipaddress                 1.0.14                   py27_0  
ipykernel                 4.3.1                    py27_0  
ipython                   4.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
jbig                      2.1                           0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py27_0  
jupyter                   1.0.0                    py27_1  
jupyter_client            4.2.2                    py27_0  
jupyter_console           4.1.1                    py27_0  
jupyter_core              4.1.0                    py27_0  
kealib                    1.4.5                         0  
krb5                      1.13.2                        0  
libffi                    3.0.13                        0  
libgdal                   2.0.0                         2  
libgfortran               3.0.0                         1  
libnetcdf                 4.3.3.1                       3  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
lxml                      3.6.0                    py27_0  
mako                      1.0.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.5.1               np110py27_0  
meld3                     1.0.2                    py27_0  
mistune                   0.7.2                    py27_0  
mkl                       11.3.3                        0  
mock                      2.0.0                    py27_0  
mongodb                   2.4.6                         0  
mpi4py                    2.0.0                    py27_1  
mpich2                    1.4.1p1                       0  
nbconvert                 4.1.0                    py27_0  
nbformat                  4.0.1                    py27_0  
esmf                      7.0.0                         3    nesii
esmpy                     7.0.0                    py27_3    nesii
icclim                    4.1.1                    py27_0    nesii
ocgis                     1.3.1                    py27_0    nesii
udunits2                  2.2.20                        0    nesii
netcdf4                   1.2.2               np110py27_0  
networkx                  1.11                     py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.1.0                    py27_1  
numpy                     1.10.4                   py27_2  
openblas                  0.2.14                        0  
openldap                  2.4.36                        1  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np110py27_0  
pango                     1.39.0                        0  
pastedeploy               1.5.2                    py27_1  
path.py                   8.1.2                    py27_1  
patsy                     0.4.0               np110py27_0  
pbr                       1.3.0                    py27_0  
pcre                      8.31                          0  
pep8                      1.7.0                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pillow                    3.1.1                    py27_0  
cloog                     0.18.0                        0    pingucarsti
gmp                       5.1.2                         5    pingucarsti
isl                       0.12.2                        1    pingucarsti
mpc                       1.0.1                         0    pingucarsti
mpfr                      3.1.2                         0    pingucarsti
wget                      1.15                          2    pingucarsti
pip                       8.1.1                    py27_0  
pixman                    0.32.6                        0  
postgresql                9.1.4                         1  
proj4                     4.9.1                         0  
ptyprocess                0.5                      py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycparser                 2.14                     py27_0  
pygments                  2.1.3                    py27_0  
pyopenssl                 0.15.1                   py27_2  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_1  
pyramid                   1.5.7                    py27_0  
pyramid_chameleon         0.3                      py27_0  
pyramid_mako              1.0.2                    py27_0  
pytest                    2.9.2                    py27_0  
pytest-cache              1.0                      py27_0  
pytest-pep8               1.0.6                    py27_0  
python                    2.7.11                        0  
python-dateutil           2.5.0                    py27_0  
python-ldap               2.4.13                   py27_0  
pytz                      2016.4                   py27_0  
pywget                    2.2                      py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     15.2.0                   py27_0  
qt                        4.8.7                         1  
qtconsole                 4.1.1                    py27_1  
ncurses                   5.9                           4    r
r                         3.2.2                         0    r
r-base                    3.2.2                         0    r
r-boot                    1.3_17                r3.2.2_0a    r
r-class                   7.3_14                r3.2.2_0a    r
r-cluster                 2.0.3                 r3.2.2_0a    r
r-codetools               0.2_14                r3.2.2_0a    r
r-foreign                 0.8_66                r3.2.2_0a    r
r-kernsmooth              2.23_15               r3.2.2_0a    r
r-lattice                 0.20_33               r3.2.2_0a    r
r-mass                    7.3_45                r3.2.2_0a    r
r-matrix                  1.2_2                 r3.2.2_0a    r
r-mgcv                    1.8_9                 r3.2.2_0a    r
r-nlme                    3.1_122               r3.2.2_0a    r
r-nnet                    7.3_11                r3.2.2_0a    r
r-recommended             3.2.2                  r3.2.2_0    r
r-rpart                   4.1_10                r3.2.2_0a    r
r-spatial                 7.3_11                r3.2.2_0a    r
r-survival                2.38_3                r3.2.2_0a    r
rpy2                      2.7.0              py27r3.2.2_0    r
readline                  6.2                           2  
redis-py                  2.10.5                   py27_0  
repoze.lru                0.6                      py27_0  
requests                  2.10.0                   py27_0  
scikit-learn              0.17.1              np110py27_1  
scipy                     0.17.0              np110py27_4  
biggus                    0.13.0                   py27_0    scitools
geos                      3.4.2                         4    scitools
libmo_unpack              3.0                           3    scitools
proj.4                    4.9.1                         1    scitools
pyshp                     1.2.3                    py27_0    scitools
setuptools                20.1.1                   py27_0  
simplegeneric             0.8.1                    py27_0  
simplejson                3.8.2                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.4.1                    py27_0  
sphinx_rtd_theme          0.1.9                    py27_0  
sqlalchemy                1.0.12                   py27_0  
sqlite                    3.9.2                         0  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1               np110py27_1  
supervisor                3.1.3                    py27_1  
system                    5.8                           2  
terminado                 0.5                      py27_1  
tk                        8.5.18                        0  
tornado                   4.3                      py27_0  
traitlets                 4.1.0                    py27_0  
transaction               1.4.4                    py27_0  
translationstring         1.3                      py27_0  
venusian                  1.0                      py27_0  
webob                     1.4.1                    py27_0  
wheel                     0.29.0                   py27_0  
xerces-c                  3.1.2                         0  
xz                        5.0.5                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  
zope.deprecation          4.1.2                    py27_0  
zope.interface            4.1.2                    py27_1  
[nhempel@lsce3199 flyingpigeon]$

**Comment by sradanov** [comment]
Failed to install with pinned r-mclust=2.2

**Comment by nilshempelmann** [comment]
r-mclust is used in weatherregimes process.
now pinned to r-mclust=5.1

**Comment by nilshempelmann** [comment]
icu=54.1

**Comment by mcalvcas** [comment]
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - libiconv 1.14*

**Comment by nilshempelmann** [comment]
done.
