### ISSUE TITLE
analog process writes data into the etc/pywps folder

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#51]
... this happens for the archive and simulation file (produced by the ocgis_module).

They should be written to the pywps temp folder which is generated by pywps for each process and is the "current dir" in the process call.

Can't see why this happens ... 

See also #48

**Comment by nilshempelmann** [comment]
set the default output folder for ocgis call from None to current directory

**Comment by nilshempelmann** [comment]
fixed by pinning the output_dir to curdir in ocgis call. 
All ocgis calles were writing into etc/pywps by default.
the compute providers need to clean up etc/pywps :-)
