### ISSUE TITLE
preparing data for weather regimes

### ISSUE THREAD

**Issue by mcalvcas** [bird-house/flyingpigeon#53]
get netcdf from a dataset and the anomalies from phyton

**Comment by nilshempelmann** [comment]
subtraction of seasonal mean requires a smoothing: 

"sousseasmean"<-function(dat,conv.time,l.mon=1:12,
                         l.year=unique(conv.time$year),rprint=FALSE)
{
  dat.m=dat
  seas.cyc=c()
  time.cyc=c()
  # Calcul du cycle saisonnier pour une liste d'annees dans l.year
  if(rprint) print("Seasonal cycle")
  for(mon in l.mon){
    r.day=range(conv.time$day[conv.time$month==mon])
    for(day in r.day[1]:r.day[2]){
      m.day=apply(dat[conv.time$day==day & conv.time$month==mon &
                        conv.time$year %in% l.year,],2,mean,na.rm=TRUE)
      seas.cyc=rbind(seas.cyc,m.day)
      time.cyc$month=c(time.cyc$month,mon)
      time.cyc$day=c(time.cyc$day,day)
    }
  }
  # Lissage par spline du cycle saisonnier avec preservation des derivees aux bords
  if(rprint) print("Seasonal cycle smoothing")
  seas.cyc.spl=rbind(seas.cyc,seas.cyc,seas.cyc)
  for(i in 1:ncol(seas.cyc)){
    seas.cyc.spl[,i]=smooth.spline(seas.cyc.spl[,i],spar=0.8)$y
  }
  seas.cyc.spl=seas.cyc.spl[(nrow(seas.cyc)+1):(2*nrow(seas.cyc)),]
  
  # Soustraction du cycle saisonnier
  if(rprint) print("Seasonal anomalies")
  for(t in 1:nrow(dat)){
    mon=conv.time$month[t]
    day=conv.time$day[t]
    ii= which(time.cyc$month %in% mon & time.cyc$day %in% day)
    dat.m[t,]=dat[t,]-seas.cyc.spl[ii,]
  }
  datsub=list(anom=dat.m,seascyc=list(seascyc=seas.cyc.spl,timecyc=time.cyc))
}# fin de la definition de fonction

**Comment by nilshempelmann** [comment]
![mbjncnlidahncflh](https://cloud.githubusercontent.com/assets/8639658/16315449/a2cce8e0-3982-11e6-8151-d5ba84e210cf.png)

That's the R - smooth ....

**Comment by nilshempelmann** [comment]
a repoduction with python. 
![smooth](https://cloud.githubusercontent.com/assets/8639658/16320816/09a57caa-399a-11e6-9d2c-b26aa817e932.png)

**Comment by nilshempelmann** [comment]
R routine is not handling different calenders:
CMIP5 dataset exists with with 365 days (no 29th feb) calenders.
HadGEM is comming with 360 days

but 'sousseasmean' expect 366 days for the annual cycle

**Comment by mcalvcas** [comment]
![noise-spline](https://cloud.githubusercontent.com/assets/19947167/16448617/b5270e5c-3df2-11e6-9739-217350cb374b.png)

**Comment by nilshempelmann** [comment]
Done ;-)
