### ISSUE TITLE
MFDataset and RequestDataset does not work for cordex (NETCDF4)

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/flyingpigeon#67]
one can not use `netCDF4.MFDataset` and `ocgis.RequestDataset`.

     ValueError: MFNetCDF4 only works with NETCDF3_* and NETCDF4_CLASSIC formatted files, not NETCDF4

**Comment by nilshempelmann** [comment]
This is related to
https://github.com/bird-house/flyingpigeon/issues/29

and pinned to netcdf4==1.2.2

**Comment by cehbrecht** [comment]
but i have:

    netcdf4  *  1.2.2               np111py27_0  defaults

**Comment by cehbrecht** [comment]
i've tried also the latest version of netcdf4 from ioos and conda-forge ... but with same result.

My cordex testdata has data_model `NETCDF4`.

cmip5 data and maybe all of the "real" cordex data of the data_model `NETCDF4_CLASSIC`. I don't know if this is true for all of cordex ... but at least for the ones i have checked. 

So ... i will use cordex testdata with `NETCDF4_CLASSIC` format for now ...

**Comment by cehbrecht** [comment]
i also downgraded the numpy version:

    netcdf4   1.2.2-np110py27_0

but no effect ...

**Comment by cehbrecht** [comment]
from the docs:

http://unidata.github.io/netcdf4-python/#netCDF4.MFDataset

> Datasets must be in NETCDF4_CLASSIC, NETCDF3_CLASSIC, NETCDF3_64BIT_OFFSET or NETCDF3_64BIT_DATA format (NETCDF4 Datasets won't work).

**Comment by nilshempelmann** [comment]
@bekozi
Isn't RequestDataset using MFDataset anyway?

**Comment by bekozi** [comment]
@nilshempelmann Yes, you are correct. `RequestDataset` is using the underlying NetCDF4 `MFDataset` object. Is it causing a problem still?

**Comment by cehbrecht** [comment]
CORDEX and CMIP5 are in classic format and supported by ``MFDataset``. Testdata needs to be adapted.

**Comment by mrlaoyueliang** [comment]
Hi, have you solved this problem? I also met with the same one.
