### ISSUE TITLE
caption disappears in monitor when switching views if job still running

### ISSUE THREAD

**Issue by KatiRG** [bird-house/flyingpigeon#99]
User can edit caption while job is running but it disappears when switching to Details view.
Caption is permanent only after job is finished.

**Comment by nilshempelmann** [comment]
That's an issue of phoenix, not flyingpigeon.

**Comment by nilshempelmann** [comment]
@KatiRG 
moved to phoenix https://github.com/bird-house/pyramid-phoenix/issues/120
